/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00488d",
        "on-primary": "#ffffff",
        "primary-container": "#005fb8",
        "on-primary-container": "#cadcff",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#a8c8ff",
        "on-primary-fixed": "#001b3d",
        "on-primary-fixed-variant": "#00468b",
        "secondary": "#2a6b2c",
        "on-secondary": "#ffffff",
        "secondary-container": "#acf4a4",
        "on-secondary-container": "#307231",
        "secondary-fixed": "#acf4a4",
        "secondary-fixed-dim": "#91d78a",
        "on-secondary-fixed": "#002203",
        "on-secondary-fixed-variant": "#0c5216",
        "tertiary": "#96000f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#bb1f21",
        "on-tertiary-container": "#ffd0cb",
        "tertiary-fixed": "#ffdad6",
        "tertiary-fixed-dim": "#ffb4ac",
        "on-tertiary-fixed": "#410003",
        "on-tertiary-fixed-variant": "#93000e",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface": "#f8f9fb",
        "on-surface": "#191c1e",
        "surface-variant": "#e0e3e5",
        "on-surface-variant": "#424752",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f8f9fb",
        "surface-dim": "#d8dadc",
        "surface-tint": "#005db5",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#a8c8ff",
        "outline": "#727783",
        "outline-variant": "#c2c6d4",
        "background": "#f8f9fb",
        "on-background": "#191c1e",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
